### ISSUE TITLE
Error making a second English subentry

### ISSUE THREAD

**Issue by Muskworker** [Rexko/rexko#177]
Tried to make "tenir dă" a subentry of "tenir" but got the same error on new and on update.

**Comment by Muskworker** [comment]
Error in question:

````
ActiveRecord::UnknownAttributeError in LexemesController#update

unknown attribute: definition_en
Rails.root: /Users/Muskwalker/Documents/Utilities/Rexko/gallery/Rexko Live

Application Trace | Framework Trace | Full Trace
app/controllers/lexemes_controller.rb:155:in `update'
Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"1KKkY54YLSlYkNIQKb3S/Zqax4EoJ9+SWbiNO0hiKtg=",
 "lexeme"=>{"dictionary_ids"=>["9"],
 "headwords_attributes"=>{"0"=>{"_destroy"=>"0",
 "form_art_x_ibran"=>"tenir",
 "descriptively_ok"=>"1",
 "prescriptively_ok"=>"1",
 "phonetic_forms_attributes"=>{"0"=>{"_destroy"=>"0",
 "form_art_x_ibran"=>"tə̃ˈir",
 "id"=>"2607"}},
 "notes_attributes"=>{"0"=>{"_destroy"=>"0",
 "content_en"=>"Paysan",
 "id"=>"353"}},
 "id"=>"3644"},
 "1"=>{"_destroy"=>"0",
 "form_art_x_ibran"=>"тенжир",
 "descriptively_ok"=>"1",
 "prescriptively_ok"=>"1",
 "phonetic_forms_attributes"=>{"0"=>{"_destroy"=>"0",
 "form_art_x_ibran"=>"tɛ̃ˈʝer",
 "id"=>"2608"}},
 "notes_attributes"=>{"0"=>{"_destroy"=>"0",
 "content_en"=>"Roesan",
 "id"=>"354"}},
 "id"=>"3645"},
 "2"=>{"_destroy"=>"0",
 "form_art_x_ibran"=>"teniér",
 "descriptively_ok"=>"1",
 "prescriptively_ok"=>"1",
 "phonetic_forms_attributes"=>{"0"=>{"_destroy"=>"0",
 "form_art_x_ibran"=>"tɛ̃ˈʝer",
 "id"=>"2609"}},
 "notes_attributes"=>{"0"=>{"_destroy"=>"0",
 "content_en"=>"Roesan Latin",
 "id"=>"355"}},
 "id"=>"3646"}},
 "subentries_attributes"=>{"0"=>{"_destroy"=>"0",
 "paradigm_art_x_ibran"=>"tenir / тенжир (teniér)",
 "part_of_speech_en"=>"v. trans.",
 "senses_attributes"=>{"0"=>{"_destroy"=>"0",
 "definition_en"=>"To hold; to have.",
 "glosses_attributes"=>{"0"=>{"_destroy"=>"false",
 "gloss_en"=>""}},
 "id"=>"4197"}},
 "etymotheses_attributes"=>{"0"=>{"_destroy"=>"0",
 "etymology_attributes"=>{"_destroy"=>"0",
 "original_language_id"=>"2",
 "etymon"=>"teneo",
 "gloss_en"=>"",
 "next_etymon_attributes"=>{"_destroy"=>"false",
 "original_language_id"=>"",
 "etymon"=>"",
 "gloss_en"=>""},
 "id"=>"1916"},
 "id"=>"1693"}},
 "id"=>"3561"},
 "1439049418"=>{"_destroy"=>"false",
 "paradigm_art_x_ibran"=>"tenir da",
 "part_of_speech_en"=>"test",
 "definition_en"=>"test"}}},
 "commit"=>"Update",
 "locale"=>"en",
 "id"=>"3406"}
````

**Comment by Muskworker** [comment]
Still in current—
````
ActiveRecord::UnknownAttributeError in LexemesController#update

unknown attribute: definition_en
Rails.root: /Users/Muskwalker/Documents/Utilities/Rexko/Rexko

Application Trace | Framework Trace | Full Trace
app/controllers/lexemes_controller.rb:151:in `update'
````

On 'new' the fail is the same but in the 'create' method, in both cases it's the line that assigns the attributes to @lexeme.

**Comment by Muskworker** [comment]
It's trying to save the definition to subentry instead of sense.

**Comment by Muskworker** [comment]
It only happens with the sense that populates by default — it looks like if you make a new sense, it assigns correctly.

**Comment by Muskworker** [comment]
There are no less than *three* partials that render the sense form.  "lexemes/sense" (used for the original subentry) and "senses/form" (used for new senses after the first) appear to work correctly.  "subentries/sense" is the broken one.

**Comment by Muskworker** [comment]
"subentries/sense" and "senses/form" are verbatim identical [!] so it must be some difference in how they're called ...
