### ISSUE TITLE
Problems with adding a lexeme to multiple dictionaries

### ISSUE THREAD

**Issue by Muskworker** [Rexko/rexko#179]
Created new dictionaries for art-021-x-ibran, art-Latn-021-x-ibran, and art-155-x-ibran.  

Attempted to create a new lexeme for all three variants simultaneously.

The result page apparently could not decide on which variant to show (all Ibran-specific data was blanked in display).

Furthermore there's a "can't dup NilClass" error when attempting to view the dictionary afterwards.
````
TypeError in DictionariesController#show

can't dup NilClass
Rails.root: /Users/Muskwalker/Documents/Utilities/Rexko/gallery/Rexko Live

Application Trace | Framework Trace | Full Trace
app/models/language.rb:93:in `dup'
app/models/language.rb:93:in `block in sort'
app/models/language.rb:92:in `sort'
app/controllers/dictionaries_controller.rb:34:in `show'
Request

Parameters:

{"locale"=>"en",
 "id"=>"23"}

**Comment by Muskworker** [comment]
Attempting to duplicate in current: behavior is identical, though headwords are now listed correctly (presumably due to 37240ebca8cdaebbb0ccde9544f2e087e03bf3f1); the problem with the others may be related.

**Comment by Muskworker** [comment]
Two separate issues - 
- Re the error message, Headword#form no longer acts quite the way you'd expect because g11n, and is returning nil sometimes (it shouldn't), presumably trying to pull for an undefined locale, instead of the dictionary's source language
- Re the information not showing, more of the same not using the data from the dictionaries' languages — but I don't think it would have displayed as expected in any case — we might need a special display (list?) for how it would appear in each dictionary it's in, not just choosing an arbitrary one at random
