### ISSUE TITLE
Adding a new language shouldn't require server restart to use it

### ISSUE THREAD

**Issue by Muskworker** [Rexko/rexko#180]
Created new languages for Ibran varieties ('art-Latn-021-x-ibran', etc.).

The new lexeme form seemed to come up okay but when adding a pronunciation it failed:

```
Started GET "/en/phonetic_forms/new?path=lexeme%5Bheadwords_attributes%5D%5B0%5D%5Bphonetic_forms_attributes%5D%5B0%5D&dictionaries%5B%5D=23&dictionaries%5B%5D=24&dictionaries%5B%5D=25" for 127.0.0.1 at 2015-07-03 15:43:44 -0600
  Processing by PhoneticFormsController#new as JS
  Parameters: {"path"=>"lexeme[headwords_attributes][0][phonetic_forms_attributes][0]", "dictionaries"=>["23", "24", "25"], "locale"=>"en"}
Rendered lexemes/_phonetic_form.html.erb (320.3ms)
Rendered phonetic_forms/_form.html.erb (320.9ms)
Completed 500 Internal Server Error in 326ms

ActionView::Template::Error (undefined method `form_art_155_x_ibran' for #<PhoneticForm:0x007fbc658421b8>):
    2:   <div class="phonetic_form">
    3:      <div class="type-text">     
    4:      <%= f.label :form, label_with_remove_option_for(t('.phonetic_form'), f) %>
    5:      <%= translatable_tag f, :text_field, :form, :source %>
    6:      </div>
    7:   </div>
    8: <% end %>
  app/helpers/application_helper.rb:273:in `block (4 levels) in translatable_tag'
  app/helpers/application_helper.rb:272:in `block (3 levels) in translatable_tag'
  app/helpers/application_helper.rb:269:in `each'
  app/helpers/application_helper.rb:269:in `block (2 levels) in translatable_tag'
  app/helpers/application_helper.rb:268:in `block in translatable_tag'
  app/helpers/application_helper.rb:256:in `translatable_tag'
  app/views/lexemes/_phonetic_form.html.erb:5:in `_app_views_lexemes__phonetic_form_html_erb__1370930560800456133_70223575631920'
  app/views/phonetic_forms/_form.html.erb:3:in `block in _app_views_phonetic_forms__form_html_erb___2252426052201678134_70223575609100'
  app/views/phonetic_forms/_form.html.erb:2:in `_app_views_phonetic_forms__form_html_erb___2252426052201678134_70223575609100'
  app/controllers/phonetic_forms_controller.rb:35:in `block (2 levels) in new'
  app/controllers/phonetic_forms_controller.rb:31:in `new'

Rendered /Users/Muskwalker/.rvm/gems/ruby-1.9.3-p545@rexko/gems/actionpack-3.1.11/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.2ms)
Rendered /Users/Muskwalker/.rvm/gems/ruby-1.9.3-p545@rexko/gems/actionpack-3.1.11/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.7ms)
Rendered /Users/Muskwalker/.rvm/gems/ruby-1.9.3-p545@rexko/gems/actionpack-3.1.11/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (5.9ms)
```

On attempting to save, it likewise failed:

```
Started POST "/en/lexemes" for 127.0.0.1 at 2015-07-03 15:45:03 -0600
  Processing by LexemesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"aU8svMCJrYH7nesXHQ9X31zN78vWaNmnYLHWqr+M3a0=", "lexeme"=>{"dictionary_ids"=>["23", "24", "25"], "headwords_attributes"=>{"0"=>{"_destroy"=>"false", "form_art_155_x_ibran"=>"faular", "form_art_cyrl_021_x_ibran"=>"вѡ̄лар", "form_art_latn_021_x_ibran"=>"faular", "form_en"=>"", "descriptively_ok"=>"1", "prescriptively_ok"=>"1"}}, "subentries_attributes"=>{"0"=>{"_destroy"=>"false", "paradigm_art_155_x_ibran"=>"faular", "paradigm_art_cyrl_021_x_ibran"=>"вѡ̄лар (faular)", "paradigm_art_latn_021_x_ibran"=>"faular", "paradigm_en"=>"", "part_of_speech_en"=>"v. trans.", "senses_attributes"=>{"0"=>{"_destroy"=>"false", "definition_en"=>"To speak (a language).", "glosses_attributes"=>{"0"=>{"_destroy"=>"false", "gloss_en"=>"", "gloss_la"=>""}}}}, "etymotheses_attributes"=>{"1435959896"=>{"etymology_attributes"=>{"_destroy"=>"false", "original_language_id"=>"2", "etymon"=>"fabulare", "gloss"=>""}}}}}}, "commit"=>"Create", "locale"=>"en"}
Completed 500 Internal Server Error in 2ms

ActiveRecord::UnknownAttributeError (unknown attribute: form_art_155_x_ibran):
  app/controllers/lexemes_controller.rb:116:in `new'
  app/controllers/lexemes_controller.rb:116:in `create'

Rendered /Users/Muskwalker/.rvm/gems/ruby-1.9.3-p545@rexko/gems/actionpack-3.1.11/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.4ms)
Rendered /Users/Muskwalker/.rvm/gems/ruby-1.9.3-p545@rexko/gems/actionpack-3.1.11/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.4ms)
Rendered /Users/Muskwalker/.rvm/gems/ruby-1.9.3-p545@rexko/gems/actionpack-3.1.11/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (5.7ms)
```

On restarting the server, behaviour was as expected.  Apparently the globalize accessors only check languages on startup (which is sensible, maybe it could 'refresh' on language create/update though).

**Comment by Muskworker** [comment]
So... right now it no longer fails with an error, it just doesn't show the field at all.
