### ISSUE TITLE
NoMethodError in Lexemes#show (unexpected nil in ApplicationHelper#spaced_render)

### ISSUE THREAD

**Issue by Muskworker** [Rexko/rexko#209]
Viewing /en/lexemes/3453:

````
NoMethodError in Lexemes#show

Showing /Users/Muskwalker/Documents/Utilities/Rexko/Rexko/app/views/shared/wiki/_construction.html.erb where line #6 raised:

undefined method `collect' for nil:NilClass
Extracted source (around line #6):

3:         authors: spaced_render(:partial => "shared/wiki/author", 
4:                                 :collection => @authors_of[construction], 
5:                                 :locals => { :construction => construction, :headword => headword }, 
6:                                 :spacer => t('shared.construction.author_spacer', default: "; ")),
7:         default: "%{construction_link} — %{authors}") %>
Trace of template inclusion: app/views/shared/wiki/_lexeme.html.erb, app/views/shared/wiki/_headword.html.erb, app/views/lexemes/show.html.erb

Rails.root: /Users/Muskwalker/Documents/Utilities/Rexko/Rexko

Application Trace | Framework Trace | Full Trace
app/helpers/application_helper.rb:159:in `spaced_render'
app/views/shared/wiki/_construction.html.erb:6:in `_app_views_shared_wiki__construction_html_erb__4255709616787803576_70177590023540'
app/views/shared/wiki/_lexeme.html.erb:4:in `_app_views_shared_wiki__lexeme_html_erb__4135587175219762330_70177601033600'
app/views/shared/wiki/_headword.html.erb:1:in `_app_views_shared_wiki__headword_html_erb__1196816355719108225_70177567179040'
app/views/lexemes/show.html.erb:27:in `block (2 levels) in _app_views_lexemes_show_html_erb___720462125644505232_70177591020720'
app/views/lexemes/show.html.erb:16:in `each'
app/views/lexemes/show.html.erb:16:in `block in _app_views_lexemes_show_html_erb___720462125644505232_70177591020720'
app/views/lexemes/show.html.erb:15:in `each'
app/views/lexemes/show.html.erb:15:in `_app_views_lexemes_show_html_erb___720462125644505232_70177591020720'
app/controllers/lexemes_controller.rb:41:in `show'
````

**Comment by Muskworker** [comment]
This is happening when there is more than one lexeme on the wiki page.  It only knows how to pull data from the main lexeme, and errors otherwise.
