### ISSUE TITLE
ActionView::MissingTemplate in Lexemes#edit

### ISSUE THREAD

**Issue by Muskworker** [Rexko/rexko#219]
````
ActionView::MissingTemplate in Lexemes#edit

Showing /Users/Muskwalker/Documents/Utilities/Rexko/gallery/Rexko Live/app/views/languages/_form.html.erb where line #13 raised:

Missing partial lexemes/sort_order, application/sort_order with {:handlers=>[:erb, :builder, :rjs], :formats=>[:html], :locale=>[:en, :en]}. Searched in:
  * "/Users/Muskwalker/Documents/Utilities/Rexko/gallery/Rexko Live/app/views"
Extracted source (around line #13):

10: 		<%= language_form.text_field :iso_639_code %>
11: 	</div>
12: 
13:   <%= list_children_with_option_to_add :sort_order, language_form, remote: true, limit_one: true %>
Trace of template inclusion: app/views/etymologies/_shortform.html.erb, app/views/lexemes/_etymology.html.erb, app/views/lexemes/_etymothesis.html.erb, app/views/subentries/_shortform.html.erb, app/views/lexemes/_subentry.html.erb, app/views/lexemes/_form.html.erb, app/views/lexemes/edit.html.erb

Rails.root: /Users/Muskwalker/Documents/Utilities/Rexko/gallery/Rexko Live

Application Trace | Framework Trace | Full Trace
app/helpers/application_helper.rb:122:in `block in list_children_with_option_to_add'
app/helpers/application_helper.rb:117:in `list_children_with_option_to_add'
app/views/languages/_form.html.erb:13:in `_app_views_languages__form_html_erb__797648241169268355_70162964254940'
app/helpers/application_helper.rb:236:in `block (2 levels) in autocomplete'
app/helpers/application_helper.rb:235:in `block in autocomplete'
app/helpers/application_helper.rb:216:in `autocomplete'
app/views/etymologies/_shortform.html.erb:6:in `_app_views_etymologies__shortform_html_erb__4290850755257589093_70162964169680'
app/views/lexemes/_etymology.html.erb:4:in `_app_views_lexemes__etymology_html_erb__1739233328956113083_70162964164360'
app/helpers/application_helper.rb:122:in `block in list_children_with_option_to_add'
app/helpers/application_helper.rb:117:in `list_children_with_option_to_add'
app/views/lexemes/_etymothesis.html.erb:7:in `_app_views_lexemes__etymothesis_html_erb___1514732291399994832_70162965739360'
app/helpers/application_helper.rb:122:in `block in list_children_with_option_to_add'
app/helpers/application_helper.rb:117:in `list_children_with_option_to_add'
app/views/subentries/_shortform.html.erb:18:in `_app_views_subentries__shortform_html_erb__3520973961983827359_70162965899440'
app/views/lexemes/_subentry.html.erb:3:in `_app_views_lexemes__subentry_html_erb___636386694725688330_70162966930320'
app/helpers/application_helper.rb:122:in `block in list_children_with_option_to_add'
app/helpers/application_helper.rb:117:in `list_children_with_option_to_add'
app/views/lexemes/_form.html.erb:12:in `block in _app_views_lexemes__form_html_erb__2080142744318292883_70162965850360'
app/views/lexemes/_form.html.erb:1:in `_app_views_lexemes__form_html_erb__2080142744318292883_70162965850360'
app/views/lexemes/edit.html.erb:3:in `_app_views_lexemes_edit_html_erb__3803705932354182720_70162965847280'
Request

Parameters:

{"locale"=>"en",
 "id"=>"3385"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by Muskworker** [comment]
This was trying to view /en/lexemes/3385/edit

**Comment by Muskworker** [comment]
Likewise /en/lexemes/3414/edit

**Comment by Muskworker** [comment]
Also /en/lexemes/3420/edit

**Comment by Muskworker** [comment]
/en/lexemes/3404/edit ...
